### ISSUE TITLE
Rate Limit On first try

### ISSUE THREAD

**Issue by SwannWilliame** [holy-crusader-py/dartagram#1]
flutter: erreur : Exception: Failed to load user profile, content type is not application/json, probably due to a rate limit

get this error on the first time using the api and the command to get the user infos

**Comment by holy-crusader-py** [comment]
Please show me your code, it's working for me

**Comment by holy-crusader-py** [comment]
Sorry, it's my fault, there was a problem with the publication of the new version.
Update the package and everything should be fine
